# Generated by Django 3.0.11 on 2020-12-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_sslcommerz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sslcommerzsession',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sslcommerzsession',
            name='tran_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sslcommerzsession',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
