# Generated by Django 3.0.11 on 2020-12-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_sslcommerz', '0002_auto_20201219_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sslcommerzsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sslcommerzsession',
            name='tran_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sslcommerzsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
