# Generated by Django 3.0.11 on 2020-12-19 06:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('django_sslcommerz', '0003_auto_20201219_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sslcommerzsession',
            name='tran_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 12, 19, 6, 49, 8, 179624, tzinfo=utc)),
        ),
    ]
